INCLUDE("${CMAKE_CURRENT_LIST_DIR}/SetUtils.cmake")
INCLUDE("${CMAKE_CURRENT_LIST_DIR}/container.cmake")

# INCLUDE("${CMAKE_CURRENT_LIST_DIR}/mpi.cmake")

SET_BOOL_CACHE_VAR(TPL_ENABLE_MPI ON)
SET_BOOL_CACHE_VAR(TPL_ENABLE_BLAS ON)
SET_BOOL_CACHE_VAR(TPL_ENABLE_LAPACK ON)
SET_BOOL_CACHE_VAR(TPL_ENABLE_HDF5 ON)
# SET_BOOL_CACHE_VAR(TPL_ENABLE_SuperLU ON)

SET_BOOL_CACHE_VAR(Netcdf_ALLOW_MODERN ON)

SET_BOOL_CACHE_VAR(BUILD_SHARED_LIBS ON)

INCLUDE("${CMAKE_CURRENT_LIST_DIR}/basePackages.cmake")
INCLUDE("${CMAKE_CURRENT_LIST_DIR}/noEpetraStack.cmake")
INCLUDE("${CMAKE_CURRENT_LIST_DIR}/pytrilinos2.cmake")
INCLUDE("${CMAKE_CURRENT_LIST_DIR}/ninja.cmake")

# SET(Trilinos_WARNINGS_MODE "WARN" CACHE STRING "Trilinos warnings mode")
